<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
# Get tensor back as python int
scalar.ndim


0

In [ ]:
# Vector
vector=torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [ ]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [ ]:
random_tensor

tensor([[[0.3101, 0.3810, 0.8615, 0.4694],
         [0.3488, 0.8925, 0.7125, 0.0712],
         [0.5573, 0.3330, 0.1490, 0.4770]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [ ]:
random_image_size_tensor

tensor([[[0.3216, 0.2133, 0.7815],
         [0.5189, 0.5060, 0.3397],
         [0.4017, 0.8751, 0.5635],
         ...,
         [0.7846, 0.3389, 0.0944],
         [0.1381, 0.2781, 0.9100],
         [0.3882, 0.5288, 0.9559]],

        [[0.5128, 0.1488, 0.1948],
         [0.6156, 0.1136, 0.3760],
         [0.0660, 0.4469, 0.1023],
         ...,
         [0.1873, 0.8898, 0.0614],
         [0.7193, 0.9859, 0.4157],
         [0.3954, 0.8198, 0.3170]],

        [[0.4897, 0.5217, 0.1092],
         [0.7335, 0.6229, 0.9702],
         [0.1106, 0.9328, 0.4674],
         ...,
         [0.2144, 0.4012, 0.7986],
         [0.3611, 0.5706, 0.4968],
         [0.3973, 0.4032, 0.7197]],

        ...,

        [[0.9281, 0.5451, 0.1837],
         [0.9997, 0.9142, 0.3946],
         [0.1711, 0.1053, 0.2185],
         ...,
         [0.9437, 0.2021, 0.1152],
         [0.9795, 0.2764, 0.5371],
         [0.0344, 0.3946, 0.2365]],

        [[0.1874, 0.6763, 0.9278],
         [0.7538, 0.8949, 0.9446],
         [0.

## Zeros and Ones

In [ ]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Use torch.range()

In [ ]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [ ]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5579, 0.3582, 0.2226, 0.4383],
        [0.7105, 0.7868, 0.2100, 0.7482],
        [0.3059, 0.2402, 0.9289, 0.6872]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.5579, 0.3582, 0.2226, 0.4383],
        [0.7105, 0.7868, 0.2100, 0.7482],
        [0.3059, 0.2402, 0.9289, 0.6872]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [ ]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor=tensor*10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([1., 2., 3.])

In [ ]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [ ]:
# Element wise  multiplication
print (f"Equals:{tensor*tensor}")
# 10*10

Equals:tensor([100, 400, 900])


In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
# manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 1.98 ms, sys: 89 µs, total: 2.07 ms
Wall time: 8.62 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 1.29 ms


tensor(1400)

In [ ]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[1.4558, 2.3648, 2.1055, 2.5112, 2.2250, 1.0521, 1.3873, 2.0012, 1.4674,
         2.5526],
        [1.6833, 2.3634, 2.7122, 2.8751, 2.6181, 1.4655, 1.5747, 2.4207, 2.2633,
         2.2756],
        [1.9613, 2.9775, 3.2322, 3.1714, 3.2465, 1.8456, 2.0563, 3.1327, 2.3818,
         3.2982],
        [2.5362, 3.7456, 4.0303, 4.1102, 3.7297, 2.0878, 2.1973, 3.1713, 3.1805,
         3.6167],
        [2.3324, 3.2458, 3.1276, 3.1276, 2.9665, 1.9908, 1.6226, 3.8678, 2.6518,
         3.3788],
        [2.1667, 3.1829, 3.2296, 3.0713, 2.9674, 1.8844, 1.5508, 2.8946, 2.5960,
         2.7343],
        [1.7649, 2.6348, 2.5391, 3.0042, 2.3512, 1.7160, 1.2755, 2.6030, 2.0753,
         2.5245],
        [1.4605, 2.4169, 2.5633, 2.5780, 2.1884, 1.3739, 1.3332, 1.7653, 1.7065,
         2.3393],
        [1.7421, 2.6128, 2.4184, 2.7796, 2.9780, 1.7967, 1.7852, 2.7234, 2.0877,
         2.8718],
        [1.9981, 2.7076, 3.5774, 3.2816, 3.1609, 1.5184, 1.9434, 2.8636, 2.4123,
         3.3313]])

In [ ]:
# Shape of tensor
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])

In [ ]:
# torch.matmul(tensor_a,tensor_b)  error will occur due to shape problem
# we can perform transpose to get solution
tensor_b=tensor_b.T

In [ ]:
torch.matmul(tensor_a,tensor_b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Find the min,max,mean,sum

In [ ]:
# Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# For finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
print(x.dtype)
x=x.float()

torch.mean(x)

torch.int64


tensor(45.)

In [ ]:
x.dtype

torch.float32

In [ ]:
# Find the sum
torch.sum(x)

tensor(450.)

### Find the positional min and max

In [ ]:
x.argmin()


tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezung tensors


*   Reshaping-reshape an input tensor to a define shape
*   View-Return a view of an imput tensor of cetain shape but keep the same memory as the original tensor
*   Stacking -combine multiple tensor on the top of each other (vstack) or side by side (hstack)
*   Squeeze - remove all `1` dimension from the tensor
* Unsqeeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a cetain way




In [ ]:
# let create the tensor
import torch
x= torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
# Add an extra reshape dimension
x_reshaped=x.reshape(3,4)
x_reshaped, x_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [ ]:
# Change the view
z=x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memroy as the original)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [ ]:
# Stack tensors on the top of the each other
x_stacked = torch.stack([x,x,x,x], dim=1)

In [ ]:
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [ ]:
# torch.squeeze () - remove all single dimensions from a target tensor
x_reshaped

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x_reshaped.squeeze()

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([3, 4])

In [ ]:
y= torch.arange(1.,13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
y_reshaped=y.reshape(1,12)
y_reshaped.shape

torch.Size([1, 12])

In [ ]:
y_reshaped.squeeze()


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
y_reshaped.squeeze().shape

torch.Size([12])

In [ ]:
#  torch.permute - rearrange the dimensions of a target in a specified order
x_original =torch.rand(size=(224, 224, 3))
x_original
# permute the original tensor to rearrange the axis(or dim) order
x_permuted=x_original.permute(2,0,1)
x_permuted

tensor([[[0.5948, 0.4344, 0.4756,  ..., 0.8583, 0.7710, 0.4318],
         [0.2871, 0.8523, 0.6158,  ..., 0.8689, 0.7003, 0.5866],
         [0.4573, 0.5716, 0.5888,  ..., 0.5284, 0.6438, 0.0207],
         ...,
         [0.2106, 0.7639, 0.6208,  ..., 0.7995, 0.6518, 0.9673],
         [0.6015, 0.4960, 0.4902,  ..., 0.8428, 0.8803, 0.8339],
         [0.1170, 0.8317, 0.8993,  ..., 0.7864, 0.4613, 0.9925]],

        [[0.7444, 0.4107, 0.3169,  ..., 0.6088, 0.3038, 0.3364],
         [0.0165, 0.9384, 0.2910,  ..., 0.8779, 0.8125, 0.5402],
         [0.7151, 0.7703, 0.5338,  ..., 0.7250, 0.8010, 0.2875],
         ...,
         [0.9525, 0.0750, 0.2552,  ..., 0.2525, 0.0685, 0.8724],
         [0.3188, 0.0202, 0.5020,  ..., 0.3216, 0.9069, 0.7097],
         [0.4362, 0.1218, 0.5363,  ..., 0.8165, 0.1214, 0.5822]],

        [[0.8730, 0.5600, 0.4319,  ..., 0.3972, 0.7441, 0.2995],
         [0.0696, 0.2575, 0.7214,  ..., 0.2498, 0.2185, 0.2939],
         [0.0885, 0.0441, 0.2777,  ..., 0.6734, 0.0307, 0.

In [ ]:
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


# **Indexing (selecting data from tensors)**
Indexing with pytorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# indexing on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# lets index on the inner bracket last dimension(dim=2)
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# Also can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all element of oth and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but oly the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of oth and 1st dimension and all valus of 2nd dimension
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index to retturn 3 6 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


# Pytorch tensor and Numpy
 Data in numpy to  in pytorch tensor-> `torch.from_numpy(ndarray)`


 Data in tensor to numpy -> `torch.Tensor.numpy`

In [184]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor= torch.from_numpy(array).type(torch.float32) # Always check ther dimension before converting

In [185]:
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [186]:
# Tensor to numpy array
tensor =torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))