<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [14]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [15]:
random_tensor

tensor([[[0.2529, 0.0205, 0.6506, 0.8393],
         [0.6139, 0.5265, 0.5464, 0.1006],
         [0.7273, 0.0061, 0.0451, 0.4210]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [18]:
random_image_size_tensor

tensor([[[0.2453, 0.7664, 0.4773],
         [0.8202, 0.0391, 0.0402],
         [0.7443, 0.5112, 0.6519],
         ...,
         [0.5933, 0.4939, 0.9142],
         [0.4259, 0.4618, 0.1976],
         [0.6743, 0.7530, 0.1372]],

        [[0.0485, 0.6352, 0.5475],
         [0.9901, 0.2144, 0.7958],
         [0.5857, 0.7264, 0.7284],
         ...,
         [0.7333, 0.6407, 0.1297],
         [0.9412, 0.4664, 0.8766],
         [0.7091, 0.9017, 0.9961]],

        [[0.8703, 0.2163, 0.7156],
         [0.2552, 0.7416, 0.0325],
         [0.9081, 0.1896, 0.5728],
         ...,
         [0.2643, 0.3835, 0.4384],
         [0.6625, 0.7941, 0.6212],
         [0.8536, 0.5021, 0.7556]],

        ...,

        [[0.7556, 0.3733, 0.1240],
         [0.6043, 0.3781, 0.5504],
         [0.4821, 0.5181, 0.8414],
         ...,
         [0.4954, 0.7543, 0.6121],
         [0.9159, 0.8650, 0.6828],
         [0.8461, 0.9714, 0.4668]],

        [[0.7500, 0.4132, 0.5791],
         [0.2291, 0.2222, 0.5691],
         [0.

## Zeros and Ones

In [19]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Use torch.range()

In [24]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [27]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [31]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9985, 0.3760, 0.0808, 0.3183],
        [0.9868, 0.4082, 0.4414, 0.6763],
        [0.0969, 0.9565, 0.1294, 0.6845]])

In [32]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.9985, 0.3760, 0.0808, 0.3183],
        [0.9868, 0.4082, 0.4414, 0.6763],
        [0.0969, 0.9565, 0.1294, 0.6845]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [33]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [34]:
tensor=tensor*10

In [35]:
tensor

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([1., 2., 3.])

In [37]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [38]:
tensor

tensor([10, 20, 30])

In [39]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [40]:
# Element wise  multiplication
print (f"Equals:{tensor*tensor}")
# 10*10

Equals:tensor([100, 400, 900])


In [41]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [42]:
# manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 1.28 ms, sys: 848 µs, total: 2.13 ms
Wall time: 8.81 ms


In [43]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 89 µs, sys: 0 ns, total: 89 µs
Wall time: 94.9 µs


tensor(1400)

In [44]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[2.6297, 1.8602, 2.7582, 2.7454, 1.7129, 3.3148, 2.8919, 1.8744, 1.9495,
         1.7599],
        [2.3007, 1.9608, 2.5475, 2.6094, 2.0548, 3.0156, 2.7636, 1.4381, 1.4452,
         1.7937],
        [2.4849, 2.6019, 3.2163, 3.3949, 1.9354, 3.5223, 3.2119, 1.8235, 2.0547,
         1.8622],
        [2.8191, 2.7306, 3.3460, 3.4029, 1.7501, 3.4460, 3.3962, 2.3771, 1.7242,
         2.0521],
        [2.8651, 1.8215, 2.8739, 2.8093, 2.1152, 2.3759, 3.0415, 2.1319, 0.9439,
         1.8278],
        [2.9751, 2.0221, 3.0541, 3.0859, 2.0457, 3.2878, 3.1379, 1.8751, 1.6622,
         1.7345],
        [3.2115, 3.1105, 3.9587, 4.4279, 2.4358, 4.2750, 3.7449, 2.3953, 2.4983,
         2.0348],
        [2.5171, 2.9795, 2.9304, 2.9866, 1.2970, 3.3999, 3.2617, 1.6697, 1.5697,
         2.0524],
        [4.2020, 3.2574, 4.2582, 4.1989, 2.5143, 4.7657, 4.6047, 2.8380, 2.0125,
         2.9251],
        [2.7870, 1.8758, 2.9327, 3.5553, 2.5856, 3.3803, 2.6340, 2.1360, 2.2640,
         1.2575]])

In [45]:
# Shape of tensor
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])

In [46]:
# torch.matmul(tensor_a,tensor_b)  error will occur due to shape problem
# we can perform transpose to get solution
tensor_b=tensor_b.T

In [47]:
torch.matmul(tensor_a,tensor_b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Find the min,max,mean,sum

In [48]:
# Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# For finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
print(x.dtype)
x=x.float()

torch.mean(x)

torch.int64


tensor(45.)

In [51]:
x.dtype

torch.float32

In [52]:
# Find the sum
torch.sum(x)

tensor(450.)

### Find the positional min and max

In [53]:
x.argmin()


tensor(0)

In [54]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezung tensors


*   Reshaping-reshape an input tensor to a define shape
*   View-Return a view of an imput tensor of cetain shape but keep the same memory as the original tensor
*   Stacking -combine multiple tensor on the top of each other (vstack) or side by side (hstack)
*   Squeeze - remove all `1` dimension from the tensor
* Unsqeeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a cetain way




In [55]:
# let create the tensor
import torch
x= torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [56]:
# Add an extra reshape dimension
x_reshaped=x.reshape(3,4)
x_reshaped, x_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [57]:
# Change the view
z=x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [58]:
# changing z changes x (because a view of a tensor shares the same memroy as the original)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [59]:
# Stack tensors on the top of the each other
x_stacked = torch.stack([x,x,x,x], dim=1)

In [60]:
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [61]:
# torch.squeeze () - remove all single dimensions from a target tensor
x_reshaped

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [62]:
x_reshaped.squeeze()

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [63]:
x_reshaped.squeeze().shape

torch.Size([3, 4])

In [64]:
y= torch.arange(1.,13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [65]:
y_reshaped=y.reshape(1,12)
y_reshaped.shape

torch.Size([1, 12])

In [66]:
y_reshaped.squeeze()


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [67]:
y_reshaped.squeeze().shape

torch.Size([12])

In [68]:
#  torch.permute - rearrange the dimensions of a target in a specified order
x_original =torch.rand(size=(224, 224, 3))
x_original
# permute the original tensor to rearrange the axis(or dim) order
x_permuted=x_original.permute(2,0,1)
x_permuted

tensor([[[0.6593, 0.8674, 0.1290,  ..., 0.2812, 0.1671, 0.0943],
         [0.0865, 0.3073, 0.1697,  ..., 0.3485, 0.1401, 0.8197],
         [0.5388, 0.2659, 0.8750,  ..., 0.9163, 0.6083, 0.4190],
         ...,
         [0.4982, 0.3989, 0.8486,  ..., 0.3364, 0.0651, 0.2209],
         [0.9856, 0.5380, 0.9634,  ..., 0.5954, 0.4955, 0.6742],
         [0.6200, 0.1328, 0.2797,  ..., 0.3660, 0.2848, 0.7352]],

        [[0.1062, 0.9357, 0.2104,  ..., 0.0848, 0.9153, 0.6408],
         [0.9292, 0.4006, 0.1227,  ..., 0.4887, 0.0499, 0.6004],
         [0.8259, 0.1569, 0.0280,  ..., 0.9475, 0.5869, 0.3691],
         ...,
         [0.8863, 0.3285, 0.1029,  ..., 0.4184, 0.0283, 0.8009],
         [0.9911, 0.9723, 0.5364,  ..., 0.0208, 0.7139, 0.9279],
         [0.2738, 0.1402, 0.9154,  ..., 0.9120, 0.0727, 0.5891]],

        [[0.0557, 0.1465, 0.4433,  ..., 0.6334, 0.2815, 0.9825],
         [0.5942, 0.2578, 0.8304,  ..., 0.8528, 0.9149, 0.8940],
         [0.1239, 0.5268, 0.3023,  ..., 0.1575, 0.8133, 0.

In [69]:
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


# **Indexing (selecting data from tensors)**
Indexing with pytorch is similar to indexing with NumPy

In [70]:
# Create a tensor
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# indexing on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [73]:
# lets index on the inner bracket last dimension(dim=2)
x[0][0][0]

tensor(1)

In [74]:
x[0][1][1]

tensor(5)

In [75]:
x[0][2][2]

tensor(9)

In [76]:
# Also can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [77]:
# get all element of oth and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [78]:
# Get all values of the 0 dimension but oly the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [79]:
# Get index 0 of oth and 1st dimension and all valus of 2nd dimension
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
# index to retturn 3 6 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


# Pytorch tensor and Numpy
 Data in numpy to  in pytorch tensor-> `torch.from_numpy(ndarray)`


 Data in tensor to numpy -> `torch.Tensor.numpy`

In [81]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor= torch.from_numpy(array).type(torch.float32) # Always check ther dimension before converting

In [82]:
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [83]:
# Tensor to numpy array
tensor =torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)
TO reduce the randomness in neural networks and Pytorch comes the concept of a **randomseed**

In [85]:
import random
# Create two random tensors
random_A= torch.rand(3,4)
random_B=torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.7014, 0.9860, 0.0724, 0.6671],
        [0.3625, 0.7775, 0.8908, 0.9156],
        [0.8004, 0.0185, 0.9082, 0.8441]])
tensor([[0.5860, 0.7903, 0.3206, 0.8408],
        [0.1859, 0.7667, 0.6089, 0.7665],
        [0.3305, 0.1602, 0.6422, 0.6824]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [89]:
import torch
# Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_C =torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C==random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
