<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [14]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [15]:
random_tensor

tensor([[[0.4686, 0.9837, 0.3400, 0.1637],
         [0.4889, 0.2489, 0.0952, 0.1375],
         [0.6233, 0.3593, 0.7103, 0.5379]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [18]:
random_image_size_tensor

tensor([[[0.7169, 0.9172, 0.2923],
         [0.7529, 0.3780, 0.1040],
         [0.8288, 0.5118, 0.9273],
         ...,
         [0.0148, 0.0636, 0.0697],
         [0.9357, 0.7949, 0.9575],
         [0.4693, 0.1301, 0.0939]],

        [[0.6960, 0.1455, 0.9785],
         [0.3390, 0.1048, 0.5008],
         [0.1328, 0.3656, 0.5078],
         ...,
         [0.2812, 0.1806, 0.9640],
         [0.6974, 0.2557, 0.3830],
         [0.9122, 0.2896, 0.6417]],

        [[0.0698, 0.4849, 0.8006],
         [0.0622, 0.3522, 0.1995],
         [0.4862, 0.0437, 0.0355],
         ...,
         [0.0193, 0.1249, 0.2269],
         [0.8288, 0.6332, 0.2524],
         [0.3169, 0.4848, 0.0646]],

        ...,

        [[0.9618, 0.0341, 0.9132],
         [0.7024, 0.1030, 0.1760],
         [0.4069, 0.5798, 0.0094],
         ...,
         [0.0478, 0.4556, 0.3541],
         [0.5327, 0.0563, 0.2360],
         [0.9725, 0.8583, 0.7477]],

        [[0.5529, 0.0656, 0.9573],
         [0.4123, 0.3750, 0.6078],
         [0.

## Zeros and Ones

In [19]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Use torch.range()

In [24]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [27]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [31]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3116, 0.7855, 0.4766, 0.4354],
        [0.9039, 0.0427, 0.6588, 0.0531],
        [0.3864, 0.3883, 0.8576, 0.8422]])

In [32]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.3116, 0.7855, 0.4766, 0.4354],
        [0.9039, 0.0427, 0.6588, 0.0531],
        [0.3864, 0.3883, 0.8576, 0.8422]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [33]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [34]:
tensor=tensor*10

In [35]:
tensor

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([1., 2., 3.])

In [37]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [38]:
tensor

tensor([10, 20, 30])

In [39]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [40]:
# Element wise  multiplication
print (f"Equals:{tensor*tensor}")
# 10*10

Equals:tensor([100, 400, 900])


In [41]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [42]:
# manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 9.7 ms, sys: 394 µs, total: 10.1 ms
Wall time: 20.9 ms


In [43]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 366 µs, sys: 0 ns, total: 366 µs
Wall time: 400 µs


tensor(1400)

In [44]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[2.8173, 2.5072, 1.9321, 3.2087, 2.2251, 3.3091, 3.2116, 2.6723, 1.5803,
         2.6914],
        [2.0415, 2.7242, 2.2517, 3.0288, 1.9203, 2.2242, 2.6003, 2.2727, 2.2689,
         2.5176],
        [3.2183, 2.6392, 2.8119, 3.5399, 3.2269, 3.0704, 3.8594, 2.9828, 2.4192,
         3.1900],
        [1.9380, 1.7961, 1.7323, 2.3469, 1.7193, 1.8660, 2.6553, 1.5192, 1.3924,
         1.7131],
        [1.7709, 1.4655, 1.5554, 1.8146, 1.3308, 1.9354, 1.7756, 1.9054, 0.8925,
         1.6154],
        [2.1084, 2.4696, 1.4291, 2.3859, 1.7207, 2.1115, 2.4882, 2.2076, 1.4378,
         1.9942],
        [2.4001, 2.0422, 2.1419, 2.9317, 2.0434, 2.3340, 2.9144, 2.2766, 1.6858,
         2.4729],
        [2.3605, 1.8376, 1.6672, 2.3021, 2.1969, 2.6539, 2.5508, 2.4953, 1.3440,
         2.3066],
        [2.7437, 2.0211, 2.1425, 2.6195, 1.6814, 2.1802, 2.5417, 2.4827, 1.2647,
         1.8770],
        [2.7993, 2.8899, 2.6129, 3.7520, 3.0258, 3.2841, 3.7521, 2.9292, 2.5057,
         3.5648]])

In [45]:
# Shape of tensor
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])

In [46]:
# torch.matmul(tensor_a,tensor_b)  error will occur due to shape problem
# we can perform transpose to get solution
tensor_b=tensor_b.T

In [47]:
torch.matmul(tensor_a,tensor_b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Find the min,max,mean,sum

In [48]:
# Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# For finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
print(x.dtype)
x=x.float()

torch.mean(x)

torch.int64


tensor(45.)

In [51]:
x.dtype

torch.float32

In [52]:
# Find the sum
torch.sum(x)

tensor(450.)

### Find the positional min and max

In [53]:
x.argmin()


tensor(0)

In [54]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezung tensors


*   Reshaping-reshape an input tensor to a define shape
*   View-Return a view of an imput tensor of cetain shape but keep the same memory as the original tensor
*   Stacking -combine multiple tensor on the top of each other (vstack) or side by side (hstack)
*   Squeeze - remove all `1` dimension from the tensor
* Unsqeeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a cetain way




In [55]:
# let create the tensor
import torch
x= torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [56]:
# Add an extra reshape dimension
x_reshaped=x.reshape(3,4)
x_reshaped, x_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [57]:
# Change the view
z=x.view(1,12)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [58]:
# changing z changes x (because a view of a tensor shares the same memroy as the original)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [59]:
# Stack tensors on the top of the each other
x_stacked = torch.stack([x,x,x,x], dim=1)

In [60]:
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [61]:
# torch.squeeze () - remove all single dimensions from a target tensor
x_reshaped

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [62]:
x_reshaped.squeeze()

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [63]:
x_reshaped.squeeze().shape

torch.Size([3, 4])

In [64]:
y= torch.arange(1.,13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [65]:
y_reshaped=y.reshape(1,12)
y_reshaped.shape

torch.Size([1, 12])

In [66]:
y_reshaped.squeeze()


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [67]:
y_reshaped.squeeze().shape

torch.Size([12])

In [68]:
#  torch.permute - rearrange the dimensions of a target in a specified order
x_original =torch.rand(size=(224, 224, 3))
x_original
# permute the original tensor to rearrange the axis(or dim) order
x_permuted=x_original.permute(2,0,1)
x_permuted

tensor([[[0.2892, 0.7025, 0.2993,  ..., 0.7112, 0.1075, 0.7167],
         [0.3967, 0.0955, 0.5907,  ..., 0.9144, 0.7829, 0.5373],
         [0.2309, 0.9099, 0.7715,  ..., 0.8150, 0.1096, 0.8025],
         ...,
         [0.7834, 0.2638, 0.9520,  ..., 0.0795, 0.0191, 0.5549],
         [0.7814, 0.0814, 0.1501,  ..., 0.9939, 0.4764, 0.2005],
         [0.3871, 0.3771, 0.7346,  ..., 0.2226, 0.4159, 0.5896]],

        [[0.7157, 0.4997, 0.7801,  ..., 0.6234, 0.5680, 0.2434],
         [0.8801, 0.4886, 0.3504,  ..., 0.6718, 0.8551, 0.9243],
         [0.1803, 0.3869, 0.7691,  ..., 0.6455, 0.0991, 0.5267],
         ...,
         [0.9471, 0.2443, 0.7158,  ..., 0.6727, 0.7393, 0.4586],
         [0.1676, 0.7135, 0.6474,  ..., 0.2367, 0.2742, 0.7914],
         [0.8285, 0.4853, 0.5500,  ..., 0.5639, 0.8801, 0.0647]],

        [[0.6075, 0.4453, 0.9286,  ..., 0.6937, 0.1132, 0.1318],
         [0.1752, 0.8720, 0.3650,  ..., 0.1911, 0.6483, 0.6642],
         [0.4260, 0.2819, 0.1797,  ..., 0.6435, 0.1278, 0.

In [69]:
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


# **Indexing (selecting data from tensors)**
Indexing with pytorch is similar to indexing with NumPy

In [70]:
# Create a tensor
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# indexing on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [73]:
# lets index on the inner bracket last dimension(dim=2)
x[0][0][0]

tensor(1)

In [74]:
x[0][1][1]

tensor(5)

In [75]:
x[0][2][2]

tensor(9)

In [76]:
# Also can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [77]:
# get all element of oth and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [78]:
# Get all values of the 0 dimension but oly the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [79]:
# Get index 0 of oth and 1st dimension and all valus of 2nd dimension
x[0,:,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
# index to retturn 3 6 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


# Pytorch tensor and Numpy
 Data in numpy to  in pytorch tensor-> `torch.from_numpy(ndarray)`


 Data in tensor to numpy -> `torch.Tensor.numpy`

In [81]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor= torch.from_numpy(array).type(torch.float32) # Always check ther dimension before converting

In [82]:
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [83]:
# Tensor to numpy array
tensor =torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducbility (trying to take random out of random)
TO reduce the randomness in neural networks and Pytorch comes the concept of a **randomseed**

In [84]:
import random
# Create two random tensors
random_A= torch.rand(3,4)
random_B=torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A==random_B)

tensor([[0.9780, 0.0704, 0.9577, 0.3400],
        [0.7980, 0.8606, 0.4920, 0.8105],
        [0.2358, 0.0400, 0.9044, 0.2661]])
tensor([[0.5262, 0.2607, 0.9654, 0.7608],
        [0.5476, 0.1733, 0.1339, 0.4712],
        [0.0219, 0.4232, 0.8116, 0.1256]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [85]:
import torch
# Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_C =torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C==random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Check for GPu acess with pytorch


In [1]:
import torch
torch.cuda.is_available()

False