<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
# Get tensor back as python int
scalar.ndim


0

In [ ]:
# Vector
vector=torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [ ]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [ ]:
random_tensor

tensor([[[0.2291, 0.7382, 0.5751, 0.5589],
         [0.3101, 0.2842, 0.0958, 0.9062],
         [0.3151, 0.3470, 0.4392, 0.6003]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [ ]:
random_image_size_tensor

tensor([[[0.4058, 0.9425, 0.7794],
         [0.7456, 0.4779, 0.7873],
         [0.5364, 0.1781, 0.4457],
         ...,
         [0.2000, 0.1329, 0.0950],
         [0.5911, 0.3094, 0.1794],
         [0.9413, 0.6731, 0.7437]],

        [[0.0493, 0.7045, 0.1396],
         [0.2614, 0.7020, 0.8319],
         [0.1134, 0.1397, 0.5963],
         ...,
         [0.9092, 0.1058, 0.2345],
         [0.5322, 0.2389, 0.0840],
         [0.1832, 0.8088, 0.7116]],

        [[0.0563, 0.5242, 0.3366],
         [0.9720, 0.4060, 0.4384],
         [0.1098, 0.9258, 0.0910],
         ...,
         [0.6351, 0.6873, 0.2182],
         [0.8250, 0.6523, 0.3333],
         [0.6850, 0.5339, 0.4945]],

        ...,

        [[0.0267, 0.2091, 0.7396],
         [0.5969, 0.4358, 0.2816],
         [0.9791, 0.0125, 0.8153],
         ...,
         [0.5258, 0.3227, 0.5326],
         [0.4801, 0.7458, 0.8989],
         [0.9141, 0.3618, 0.5327]],

        [[0.4101, 0.6479, 0.5336],
         [0.5792, 0.4622, 0.5684],
         [0.

## Zeros and Ones

In [ ]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Use torch.range()

In [ ]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [ ]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0375, 0.4137, 0.3131, 0.4838],
        [0.9040, 0.1997, 0.6416, 0.7608],
        [0.8581, 0.3832, 0.7375, 0.8436]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.0375, 0.4137, 0.3131, 0.4838],
        [0.9040, 0.1997, 0.6416, 0.7608],
        [0.8581, 0.3832, 0.7375, 0.8436]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [ ]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor=tensor*10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([1., 2., 3.])

In [ ]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [ ]:
# Matrix multiplication
