<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [14]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [15]:
random_tensor

tensor([[[0.0910, 0.1670, 0.3879, 0.0381],
         [0.8265, 0.7281, 0.0653, 0.1505],
         [0.1598, 0.1410, 0.9740, 0.5634]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [18]:
random_image_size_tensor

tensor([[[0.9619, 0.3961, 0.6560],
         [0.7912, 0.3119, 0.4988],
         [0.7445, 0.2027, 0.6589],
         ...,
         [0.2895, 0.6340, 0.0680],
         [0.1684, 0.2284, 0.3024],
         [0.7167, 0.2157, 0.0811]],

        [[0.7053, 0.5581, 0.3444],
         [0.0352, 0.5763, 0.1785],
         [0.0664, 0.2335, 0.4563],
         ...,
         [0.0306, 0.6446, 0.6350],
         [0.1136, 0.5085, 0.4452],
         [0.8193, 0.6452, 0.8517]],

        [[0.6965, 0.3398, 0.9233],
         [0.0513, 0.9234, 0.3168],
         [0.2638, 0.9010, 0.9526],
         ...,
         [0.5867, 0.4695, 0.2908],
         [0.9443, 0.7900, 0.3614],
         [0.5040, 0.4872, 0.5238]],

        ...,

        [[0.0227, 0.0795, 0.5192],
         [0.5030, 0.5279, 0.3172],
         [0.4844, 0.7530, 0.8378],
         ...,
         [0.0823, 0.4909, 0.7871],
         [0.5344, 0.2400, 0.0330],
         [0.1314, 0.4824, 0.4109]],

        [[0.8461, 0.9395, 0.7317],
         [0.4498, 0.6288, 0.3978],
         [0.

## Zeros and Ones

In [19]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Use torch.range()

In [24]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype
2.   Tensors not right shape
3.   Tensors not on the right types



In [29]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [32]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)