<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [14]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [15]:
random_tensor

tensor([[[0.5141, 0.3023, 0.1232, 0.8288],
         [0.5960, 0.3717, 0.0851, 0.1924],
         [0.9103, 0.3867, 0.2550, 0.9612]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [18]:
random_image_size_tensor

tensor([[[0.9321, 0.2511, 0.0661],
         [0.1562, 0.9554, 0.2983],
         [0.4593, 0.7951, 0.4501],
         ...,
         [0.4420, 0.2209, 0.4982],
         [0.5345, 0.4876, 0.2301],
         [0.6621, 0.3785, 0.3634]],

        [[0.5556, 0.5551, 0.3708],
         [0.2772, 0.6432, 0.6848],
         [0.6465, 0.6563, 0.9706],
         ...,
         [0.6457, 0.9089, 0.7190],
         [0.2411, 0.6009, 0.0349],
         [0.3383, 0.1413, 0.4987]],

        [[0.9295, 0.8131, 0.0166],
         [0.1850, 0.8246, 0.8853],
         [0.9274, 0.9882, 0.5127],
         ...,
         [0.7691, 0.7346, 0.7839],
         [0.8870, 0.3504, 0.2012],
         [0.9264, 0.4865, 0.3389]],

        ...,

        [[0.1673, 0.9442, 0.2091],
         [0.0658, 0.8264, 0.4266],
         [0.6726, 0.5580, 0.7933],
         ...,
         [0.9474, 0.9116, 0.2204],
         [0.2407, 0.9980, 0.1128],
         [0.7175, 0.0839, 0.6691]],

        [[0.6162, 0.9914, 0.1366],
         [0.0216, 0.4301, 0.5923],
         [0.

## Zeros and Ones

In [19]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Use torch.range()

In [24]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [27]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [31]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4476, 0.0165, 0.1392, 0.1368],
        [0.8767, 0.9260, 0.5879, 0.7176],
        [0.3588, 0.1024, 0.6398, 0.3465]])

In [32]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.4476, 0.0165, 0.1392, 0.1368],
        [0.8767, 0.9260, 0.5879, 0.7176],
        [0.3588, 0.1024, 0.6398, 0.3465]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [33]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [34]:
tensor=tensor*10

In [35]:
tensor

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([1., 2., 3.])

In [37]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [38]:
tensor

tensor([10, 20, 30])

In [39]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [40]:
# Element wise  multiplication
print (f"Equals:{tensor*tensor}")
# 10*10

Equals:tensor([100, 400, 900])


In [41]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [42]:
# manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 2.22 ms, sys: 0 ns, total: 2.22 ms
Wall time: 3.27 ms


In [43]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 470 µs, total: 470 µs
Wall time: 382 µs


tensor(1400)

In [44]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[2.8944, 1.9047, 1.9582, 2.1085, 2.4777, 1.9319, 2.3733, 1.4731, 2.1237,
         2.5215],
        [3.3087, 2.4920, 2.8125, 2.7326, 2.8406, 1.9486, 3.2049, 1.8394, 2.4491,
         2.3798],
        [2.8170, 2.6537, 1.9504, 2.0683, 1.8037, 2.1510, 2.8850, 1.3363, 1.6469,
         2.2273],
        [3.7384, 2.6191, 2.9019, 3.1548, 2.5589, 2.4774, 3.2139, 2.0495, 2.4499,
         2.9081],
        [3.2035, 2.5604, 2.1571, 2.0388, 2.3641, 1.9332, 3.0198, 1.5033, 1.8999,
         2.1434],
        [3.1998, 3.1005, 2.2456, 2.9474, 2.0209, 2.3704, 3.1664, 1.6189, 2.2035,
         2.5181],
        [3.2133, 1.7939, 2.4210, 2.1646, 1.8521, 2.2587, 2.7929, 1.4232, 1.7540,
         2.2299],
        [2.8063, 2.2561, 1.9339, 2.1167, 1.6670, 1.9542, 2.5513, 1.2304, 1.7626,
         2.1291],
        [3.5252, 2.5056, 2.0685, 2.5359, 2.0725, 2.3498, 3.3036, 1.2438, 2.0684,
         2.3553],
        [3.5955, 1.9772, 2.5314, 2.6091, 2.4384, 2.1780, 2.7276, 1.8211, 1.9188,
         2.5673]])

In [45]:
# Shape of tensor
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])

In [46]:
# torch.matmul(tensor_a,tensor_b)  error will occur due to shape problem
# we can perform transpose to get solution
tensor_b=tensor_b.T

In [47]:
torch.matmul(tensor_a,tensor_b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Find the min,max,mean,sum

In [48]:
# Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# For finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
print(x.dtype)
x=x.float()

torch.mean(x)

torch.int64


tensor(45.)

In [51]:
x.dtype

torch.float32

In [52]:
# Find the sum
torch.sum(x)

tensor(450.)

### Find the positional min and max

In [53]:
x.argmin()


tensor(0)

In [54]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezung tensors


*   Reshaping-reshape an input tensor to a define shape
*   View-Return a view of an imput tensor of cetain shape but keep the same memory as the original tensor
*   Stacking -combine multiple tensor on the top of each other (vstack) or side by side (hstack)
*   Squeeze - remove all `1` dimension from the tensor
* Unsqeeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a cetain way




In [55]:
# let create the tensor
import torch
x=
