<a href="https://colab.research.google.com/github/Asmit-Dhakal/Deep_learning/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [10]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensor
`start with random numbers-> Looks at data -> updagte random numbers -> look at data -> update random numbers `

In [14]:
### Random tensor of size and shape (3,4)

random_tensor= torch.rand(1,3,4)


In [15]:
random_tensor

tensor([[[0.7756, 0.7473, 0.6416, 0.5691],
         [0.3730, 0.4758, 0.4899, 0.3342],
         [0.0488, 0.3255, 0.9290, 0.1683]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels(R G B)

In [18]:
random_image_size_tensor

tensor([[[1.8389e-01, 1.9394e-01, 9.0170e-01],
         [5.0174e-01, 2.9829e-01, 9.8427e-01],
         [7.9507e-01, 3.9825e-02, 1.2805e-01],
         ...,
         [6.4245e-01, 9.1584e-02, 8.5843e-01],
         [7.6544e-01, 7.3439e-01, 8.2612e-01],
         [6.4812e-01, 1.3455e-01, 3.0955e-01]],

        [[6.7546e-01, 6.4347e-01, 1.4604e-01],
         [5.4531e-01, 2.9476e-01, 7.4809e-01],
         [9.0731e-01, 3.1667e-01, 5.3090e-04],
         ...,
         [6.7746e-01, 6.9361e-01, 9.8328e-01],
         [8.1688e-01, 7.4586e-01, 8.4198e-01],
         [9.7586e-01, 3.3629e-01, 4.4509e-01]],

        [[9.1759e-01, 8.9684e-01, 6.7292e-01],
         [1.9227e-01, 4.9707e-01, 9.8529e-01],
         [1.1719e-01, 4.3576e-01, 7.5776e-01],
         ...,
         [6.9686e-01, 5.5342e-01, 1.8926e-01],
         [1.7201e-01, 4.7279e-02, 8.5452e-01],
         [2.3226e-01, 7.5610e-01, 2.4031e-01]],

        ...,

        [[7.5705e-01, 1.0665e-01, 6.1972e-01],
         [8.3039e-01, 2.5878e-01, 3.2125e-01]

## Zeros and Ones

In [19]:
# Create the tensors of o
zeros = torch.zeros(size=(3,4))

In [20]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create the tensor of ones
ones = torch.ones(size=(3,4))

In [22]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Use torch.range()

In [24]:
one_to_ten=torch.arange(start=0 ,end= 10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes
 Most probable error on tensor

1.   Tensor not  right datatype - check using `tensor.dtype`
2.   Tensors not right shape - check using `tensor.shape`
3.   Tensors not on the right types - check using `tensor.device`



In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,# what datatype is the tensor (eg: float32 or flaot16)
                             device=None, # What device is your tensor on
                        requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [27]:
# Conversion
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [31]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2561, 0.2109, 0.1070, 0.5480],
        [0.7243, 0.2976, 0.7192, 0.6473],
        [0.6284, 0.0119, 0.4659, 0.6911]])

In [32]:
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tenosr: {some_tensor.shape}")
print(f"Device tensor which? :{some_tensor.device}")

tensor([[0.2561, 0.2109, 0.1070, 0.5480],
        [0.7243, 0.2976, 0.7192, 0.6473],
        [0.6284, 0.0119, 0.4659, 0.6911]])
Datatype of tensor : torch.float32
Shape of tenosr: torch.Size([3, 4])
Device tensor which? :cpu


# Manipulating Tensors (tensor operations)
Tensor operation include


*   Addition
*   Substraction
*   Multiplication (element-wise)
*   Division
*   Matrix muliplication



In [33]:
# Create a tensor and operate it
tensor=torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [34]:
tensor=tensor*10

In [35]:
tensor

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([1., 2., 3.])

In [37]:
# pytorch in-built function
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [38]:
tensor

tensor([10, 20, 30])

In [39]:
torch.add(tensor,1)

tensor([11, 21, 31])

### Matrix multiplication
two ways

1. Element wise multiplication
2. Matrix wise multiplication

In [40]:
# Element wise  multiplication
print (f"Equals:{tensor*tensor}")
# 10*10

Equals:tensor([100, 400, 900])


In [41]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [45]:
# manually
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(1400)
CPU times: user 3.12 ms, sys: 10 µs, total: 3.13 ms
Wall time: 5.44 ms


In [46]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 119 µs, sys: 0 ns, total: 119 µs
Wall time: 125 µs


tensor(1400)

In [47]:
torch.matmul(torch.rand(10,10), torch.rand(10,10))

tensor([[2.1925, 1.9202, 2.8830, 3.0875, 2.3653, 1.1268, 2.5222, 3.0885, 3.2071,
         2.6456],
        [2.6160, 1.4425, 2.7560, 2.5092, 1.9255, 0.7401, 2.1372, 2.4911, 2.3029,
         2.3738],
        [2.1845, 1.9266, 2.8930, 2.5529, 2.4369, 1.0314, 2.3707, 2.5885, 2.7764,
         2.7352],
        [2.3330, 2.1849, 3.4178, 3.2169, 2.6939, 1.1186, 2.6984, 3.1741, 3.6990,
         3.0970],
        [1.5308, 1.0026, 1.4678, 1.2920, 2.1208, 0.5961, 2.1236, 2.3718, 2.5412,
         1.7012],
        [3.3518, 2.4372, 3.4945, 4.0276, 3.1466, 1.4814, 3.9303, 4.5983, 4.5722,
         3.7206],
        [1.9937, 1.9693, 3.0011, 2.6119, 2.5963, 1.0858, 2.6695, 2.9662, 3.4209,
         2.4157],
        [1.7355, 1.9283, 2.1104, 2.3197, 2.3365, 0.9805, 2.4412, 2.7474, 3.1383,
         2.7496],
        [2.7237, 2.4414, 2.8138, 2.8938, 2.7348, 1.2263, 3.4165, 3.6860, 4.2333,
         3.0763],
        [2.8270, 2.1442, 2.9416, 3.2386, 2.0388, 0.9994, 2.6738, 3.2508, 3.0569,
         2.3855]])

In [49]:
# Shape of tensor
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])

In [54]:
# torch.matmul(tensor_a,tensor_b)  error will occur due to shape problem
# we can perform transpose to get solution
tensor_b=tensor_b.T

In [55]:
torch.matmul(tensor_a,tensor_b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Find the min,max,mean,sum

In [57]:
# Create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
# For finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
print(x.dtype)
x=x.float()

torch.mean(x)

torch.int64


tensor(45.)

In [60]:
x.dtype

torch.int64

In [63]:
# Find the sum
torch.sum(x)

tensor(450.)

### Find the positional min and max

In [65]:
x.argmin()


tensor(0)

In [67]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezung tensors


*   Reshaping-reshape an input tensor to a define shape
*   View-Return a view of an imput tensor of cetain shape but keep the same memory as the original tensor
*   Stacking -combine multiple tensor on the top of each other (vstack) or side by side (hstack)



In [ ]:
## Reshaping